"""Add bio and avatar_url to User model

Revision ID: 98765172b3f7
Revises: a44986c677ad
Create Date: 2025-07-09 12:06:21.268043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98765172b3f7'
down_revision = 'a44986c677ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
