"""Add Notification model

Revision ID: a44986c677ad
Revises: 
Create Date: 2025-07-09 11:57:02.900027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a44986c677ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='unique_like')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('IsCreator',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('email',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('IsCreator',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    op.drop_table('likes')
    op.drop_table('notifications')
    # ### end Alembic commands ###
